# Generated by Django 4.2.3 on 2023-07-30 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_alter_ingredient_name_alter_recipe_tags_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredientamount",
            options={"verbose_name": "Пропорция", "verbose_name_plural": "Пропорции"},
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={"verbose_name": "Рецепт", "verbose_name_plural": "Рецепты"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.AlterField(
            model_name="ingredientamount",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_amount",
                to="recipes.ingredient",
                verbose_name="Ингредиент",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientamount",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_amount",
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
    ]
