# Generated by Django 4.2.3 on 2023-08-03 11:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0006_alter_follow_options_alter_ingredient_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={
                "ordering": ["-author_id"],
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ("name",),
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-pub_date",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("pk",),
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.AlterField(
            model_name="ingredientamount",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1, "Должно быть больше 0"),
                    django.core.validators.MaxValueValidator(
                        32000, "Максимальное количество - 32000"
                    ),
                ],
                verbose_name="Количество в рецепте",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="carts",
            field=models.ManyToManyField(
                blank=True,
                related_name="carts_recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Корзина",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Время приготовления не может быть меньше минуты"
                    ),
                    django.core.validators.MaxValueValidator(
                        32000, message="32000 минут? Слишком много"
                    ),
                ],
                verbose_name="Время приготовления",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Избранное",
            ),
        ),
    ]
